
services:
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "8080:5173"
    environment:
      # Setze die Umgebungsvariablen f端r die Frontend-Anwendung 端bernommen von start-dev.ps1
      - VITE_FINANCEAPI_URL=${VITE_FINANCEAPI_URL}
      - VITE_ASTROAPI_URL=${VITE_ASTROAPI_URL}
      - VITE_HOSTSYSTEM=${VITE_HOSTSYSTEM}
      - VITE_HOST_IP=${VITE_HOST_IP}  # Umgebungsvariable f端r die IP des Host-Laptops
    restart: unless-stopped

  astro_api:
    build: ./backend/astro_api
    container_name: astro-backend
    ports:
      - "8001:8000"
    restart: unless-stopped

  finance_api:
    build: ./backend/finance_api
    container_name: finance-backend
    ports:
      - "8002:8000"
    environment:
      - HOST_LAPTOP_IP=${VITE_HOST_IP}  # Umgebungsvariable f端r die IP des Host-Laptops
    restart: unless-stopped
